### ISSUE TITLE
HTTPS implementation on vike-node

### ISSUE THREAD

**Issue by fortezhuo** [vikejs/vike-node#1]
Hi,
Thanks for provide nice plugin..

But I encounter some issue when I need to enable https. The HMR will be broken 

```
your current setup:
  (browser) dev.example.com:8008/ <--[HTTP]--> localhost:3000/ (server)
  (browser) dev.example.com:8008/__vite_hmr <--[WebSocket (failing)]--> localhost:3000/ (server)
Check out your Vite / network configuration and 
```

```
const vite = await import("vite")

  const key = process.env.SSL_KEY!
  const cert = process.env.SSL_CERT!

  const https =
    !!key && !!cert
      ? {
          key: fs.readFileSync(key),
          cert: fs.readFileSync(cert),
        }
      : undefined

  const viteDevMiddleware = (
    await vite.createServer({
      server: {
        middlewareMode: true,
        https,
      },
    })
  ).middlewares
```

Before I install this package, I will define https on viteDevServerMiddleware. How I implement https using vike-node

**Comment by nitedani** [comment]
Hi!

This works for me with express, but if it doesn't work for you, please share a bit more of your server entry file:
```js
import express from 'express'
import https from 'https'
import { vike } from 'vike-node/connect'
import { readFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

startServer()
const __dirname = dirname(fileURLToPath(import.meta.url))

async function startServer() {
  const app = express()
  app.use(vike())
  const port = process.env.PORT || 3000
  https
    .createServer(
      {
        key: readFileSync(join(__dirname, './my-key.key'), 'utf-8'),
        cert: readFileSync(join(__dirname, './my-crt.crt'), 'utf-8')
      },
      app
    )
    .listen(port)
  console.log(`Server running at https://localhost:${port}`)
}

```

**Comment by nitedani** [comment]
Without vike-node `vite.createServer` is creating a separate server just for websocket/hmr, [by default listening on port 24678](https://github.com/vitejs/vite/blob/1025bb6d8f21c0cb9fe72405d42e0f91bb3f1d8e/packages/vite/src/node/server/ws.ts#L129).

With vike-node, there is no extra server created for vite websocket/hmr, it uses your already existing server(express, etc..).
So if you had a workaround before to get the websocket connection working on port 24678, it's no longer needed, because vite websocket connects through your main server.

**Comment by fortezhuo** [comment]
Hi!
Thanks for your quick response. I have solved this issue by adding https config on fastify instance.
I will close this issue
