### ISSUE TITLE
schema.prisma file in dist is out of date after build

### ISSUE THREAD

**Issue by jasonhilldm** [vikejs/vike-node#17]
I am experimenting with vike-node and have a test app which uses prisma. When I deploy the app to a public node server via a Circle CI, I am finding that the prisma schema is out of date with the one in my repo as there is a field that is missing and so my queries fail.

When i look at the file dist/server/node_modules/.prisma/client/schema.prisma, I can see that it is an old version of the schema that is missing a field (the field was added by a migration). I am not sure where/how the build is picking up this old schema though as I have an up to date file in my source prisma/schema.prisma file.

Is there some magic happening as part of vike-node that is constructing the schema file in the dist folder?

**Comment by brillout** [comment]
Can you provide a minimal reproduction?

**Comment by brillout** [comment]
>  it just seems to be happening as part of a Circle CI build process, i.e. if I run npm run buiild on my dev computer, then the schema in the dist folder is correct.

This makes me think it's a user land issue and not a `vike-node` one.

Closing but let's re-open if you have more evidence it's `vike-node` related.

Make sure to follow https://brillout.github.io/rules/#unrelated on Vike's GitHub, thanks.

**Comment by jasonhilldm** [comment]
Yeah, I agree it could be user land issue...are you able to advise how those prisma files get into the dist folder though? That would help me try and figure out what is causing it and if it is any way related to vike-node?

**Comment by brillout** [comment]
That said, maybe we should be improving the documentation e.g. something like https://github.com/brillout/vite-plugin-server-entry#how-it-works. I'm working on other priorities right now, but I'll be polishing `vike-node` once I've more capacity. In a nutshell: in your CI, prisma seems to modify your `node_modules/`  *after* you build your app which explains why you see a discrepancy. Btw. sponsoring welcome if you want a more tight-knit assistance from us. Otherwise follow https://brillout.github.io/rules#try but feel free to reach out if you hit a blocker you can't solve after digging a *lot* (including reading `vike-node`'s source code). Maybe we should add a note that `vike-node` is experimental.
